# 是否显示进度
print-progress: true

# 并发线程数
concurrent: 20

# 检查间隔(分钟)
check-interval: 30

# 超时时间(毫秒)(节点的最大延迟)
timeout: 5000

# 测速地址(注意 并发数*节点速度<最大网速 否则测速结果不准确)
# 尽量不要使用Speedtest，Cloudflare提供的下载链接，因为很多节点屏蔽测速网站
# 建议使用自己上传到Cloudflare R2的文件
speed-test-url: https://gh-proxy.henryjiu.workers.dev/https://github.com/AaronFeng753/Waifu2x-Extension-GUI/releases/download/v2.21.12/Waifu2x-Extension-GUI-v2.21.12-Portable.7z

# 最低测速结果舍弃(KB/s)
min-speed: 1024

# 下载测试时间(s)(与下载链接大小相关，默认最大测试10s)
download-timeout: 10

# 监听端口，用于直接返回节点信息，方便订阅转换
# http://127.0.0.1:8199/all.yaml
# 注意：为方便小白默认监听0.0.0.0:8199，请自行修改
listen-port: ":8199"

# 以节点IP查询位置重命名节点
# 质量差的节点可能造成IP查询失败，造成整体检查速度稍微变慢，默认false
rename-node: false

# 保留之前测试成功的节点
# 如果为true，则保留之前测试成功的节点，这样就不会因为上游链接更新，导致可用的节点被清除掉
keep-success-proxies: false

# 输出目录
# 如果为空，则为程序所在目录的config目录
output-dir: "./output.yaml"

# mihomo api url(测试完成后自动更新mihomo订阅)
mihomo-api-url: ""

# mihomo api secret
mihomo-api-secret: ""

# 保存方法
# 目前支持的保存方法: r2, local, gist, webdav
save-method: local

# webdav
webdav-url: "https://example.com/dav/"
webdav-username: "admin"
webdav-password: "admin"

# gist id
github-gist-id: ""

# github token
github-token: ""

# github api mirror
github-api-mirror: ""

# 将测速结果推送到Worker的地址
worker-url: https://example.worker.dev

# Worker令牌
worker-token: 1234567890

# 重试次数(获取订阅失败后重试次数)
sub-urls-retry: 3

# 订阅地址 支持 clash/mihomo/v2ray/base64 格式的订阅链接
# 如果用户想使用clash类型，那可以在支持的订阅链接结尾加上 &flag=clash.meta
sub-urls:
  - "https://slink.ltd/https://raw.githubusercontent.com/firefoxmmx2/v2rayshare_subcription/main/subscription/clash_sub.yaml"
  - "https://slink.ltd/https://raw.githubusercontent.com/Roywaller/clash_subscription/refs/heads/main/clash_subscription.txt"
  - "https://slink.ltd/https://raw.githubusercontent.com/Q3dlaXpoaQ/V2rayN_Clash_Node_Getter/refs/heads/main/APIs/sc0.yaml"
  - "https://slink.ltd/https://raw.githubusercontent.com/Q3dlaXpoaQ/V2rayN_Clash_Node_Getter/refs/heads/main/APIs/sc1.yaml"
  - "https://slink.ltd/https://raw.githubusercontent.com/Q3dlaXpoaQ/V2rayN_Clash_Node_Getter/refs/heads/main/APIs/sc2.yaml"
  - "https://slink.ltd/https://raw.githubusercontent.com/Q3dlaXpoaQ/V2rayN_Clash_Node_Getter/refs/heads/main/APIs/sc3.yaml"
  - "https://slink.ltd/https://raw.githubusercontent.com/Q3dlaXpoaQ/V2rayN_Clash_Node_Getter/refs/heads/main/APIs/sc4.yaml"
  - "https://slink.ltd/https://raw.githubusercontent.com/xiaoji235/airport-free/refs/heads/main/clash/naidounode.txt"
  - "https://slink.ltd/https://raw.githubusercontent.com/xiaoer8867785/jddy5/refs/heads/main/data/{Y_m_d}/{x}.yaml"
  - "https://slink.ltd/https://raw.githubusercontent.com/mahdibland/ShadowsocksAggregator/master/LogInfo.txt|links"
  - "https://slink.ltd/https://raw.githubusercontent.com/tglaoshiji/nodeshare/refs/heads/main/{Y}/{m}/{Ymd}.yaml"
  - "https://slink.ltd/https://raw.githubusercontent.com/mahdibland/SSAggregator/master/sub/sub_merge_yaml.yml"
  - "https://slink.ltd/https://raw.githubusercontent.com/mahdibland/ShadowsocksAggregator/master/Eternity.yml"
  - "https://slink.ltd/https://raw.githubusercontent.com/vxiaov/free_proxies/main/clash/clash.provider.yaml"
  - "https://slink.ltd/https://raw.githubusercontent.com/wangyingbo/yb_clashgithub_sub/main/clash_sub.yml"
  - "https://slink.ltd/https://raw.githubusercontent.com/ljlfct01/ljlfct01.github.io/refs/heads/main/节点"
  - "https://slink.ltd/https://raw.githubusercontent.com/snakem982/proxypool/main/source/clash-meta.yaml"
  - "https://slink.ltd/https://raw.githubusercontent.com/leetomlee123/freenode/refs/heads/main/README.md"
  - "https://slink.ltd/https://raw.githubusercontent.com/chengaopan/AutoMergePublicNodes/master/list.yml"
  - "https://slink.ltd/https://raw.githubusercontent.com/ermaozi/get_subscribe/main/subscribe/clash.yml"
  - "https://slink.ltd/https://raw.githubusercontent.com/zhangkaiitugithub/passcro/main/speednodes.yaml"
  - "https://slink.ltd/https://raw.githubusercontent.com/skka3134/test/refs/heads/main/clash.yaml|links"
  - "https://slink.ltd/https://raw.githubusercontent.com/mgit0001/test_clash/refs/heads/main/heima.txt"
  - "https://slink.ltd/https://raw.githubusercontent.com/mai19950/clashgithub_com/refs/heads/main/site"
  - "https://slink.ltd/https://raw.githubusercontent.com/aiboboxx/clashfree/refs/heads/main/clash.yml"
  - "https://slink.ltd/https://raw.githubusercontent.com/aiboboxx/v2rayfree/refs/heads/main/README.md"
  - "https://slink.ltd/https://raw.githubusercontent.com/Pawdroid/Free-servers/refs/heads/main/sub"
  - "https://slink.ltd/https://raw.githubusercontent.com/shahidbhutta/Clash/refs/heads/main/Router"
  - "https://slink.ltd/https://raw.githubusercontent.com/peasoft/NoMoreWalls/master/list.meta.yml"
  - "https://slink.ltd/https://raw.githubusercontent.com/skka3134/test/refs/heads/main/test.yaml"
  - "https://slink.ltd/https://raw.githubusercontent.com/anaer/Sub/refs/heads/main/clash.yaml"
  - "https://slink.ltd/https://raw.githubusercontent.com/a2470982985/getNode/main/clash.yaml"
  - "https://slink.ltd/https://raw.githubusercontent.com/free18/v2ray/refs/heads/main/c.yaml"
  - "https://slink.ltd/https://raw.githubusercontent.com/peasoft/NoMoreWalls/master/list.yml"
  - "https://slink.ltd/https://raw.githubusercontent.com/mfbpn/tg_mfbpn_sub/main/trial.yaml"
  - "https://slink.ltd/https://raw.githubusercontent.com/Ruk1ng001/freeSub/main/clash.yaml"
  - "https://raw.githubusercontent.com/SoliSpirit/v2ray-configs/main/all_configs.txt|links"
  - "https://slink.ltd/https://raw.githubusercontent.com/ripaojiedian/freenode/main/clash"
  - "https://slink.ltd/https://raw.githubusercontent.com/go4sharing/sub/main/sub.yaml"
  - "https://slink.ltd/https://raw.githubusercontent.com/mfuu/v2ray/master/clash.yaml"
  - "https://api.mxlweb.xyz/sub?target=clash&url=https://www.xrayvip.com/free.yaml&insert=false"
  - "https://api.mxlweb.xyz/sub?target=clash&url=https://mxlsub.me/free&insert=false"
  - "https://www.freeclashnode.com/uploads/{Y}/{m}/0-{Ymd}.yaml"
  - "https://www.freeclashnode.com/uploads/{Y}/{m}/1-{Ymd}.yaml"
  - "https://clashgithub.com/wp-content/uploads/rss/{Ymd}.yml"
  - "https://sub.reajason.eu.org/clash.yaml"
  - "https://clash.221207.xyz/pubclashyaml"
  - "https://clash.llleman.com/clach.yml"
  - "https://proxypool.link/trojan/sub"
  - "https://proxypool.link/ss/sub|ss"
  - "https://proxypool.link/vmess/sub"
  - "https://mxlsub.me/newfull"
  - "https://igdux.top/5Hna"

